import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/context/theme-provider";
import { NeonAuthUIProvider } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import { logger } from "@/lib/logger";
import { Separator } from "@/components/shadcn/separator";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Nifty Assignments",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} antialiased overflow-x-hidden`}
            >
                <NeonAuthUIProvider
                    authClient={authClient}
                    emailOTP
                    emailVerification
                    credentials={{ confirmPassword: true, }}
                    social={{
                        providers: ['google', 'github', 'vercel',]
                    }}
                    redirectTo="/account"
                >
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        

                        <main className="flex flex-1 max-w-screen flex-col gap-4 p-0 pt-0 overflow-x-hidden">
                            {children}
                        </main>

                    </ThemeProvider>
                </NeonAuthUIProvider>
            </body>
        </html >
    );
}
