import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/navigation/sidebar";
import Header from "@/components/navigation/header";
import { SidebarInset, SidebarProvider } from "@/components/shadcn/sidebar";
import { ThemeProvider } from "@/context/theme-provider";
import { NeonAuthUIProvider } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Nifty Assignments",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NeonAuthUIProvider
                    authClient={authClient}
                    emailOTP
                    emailVerification
                    social={{
                        providers: ['google', 'github', 'vercel']
                    }}
                    redirectTo="/account"
                >


                    <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
                        <SidebarProvider>
                            <AppSidebar />
                            <SidebarInset>
                                <Header />
                                <main className="flex flex-1 max-w-screen flex-col gap-4 p-4 pt-0 overflow-hidden">
                                    {children}
                                </main>
                            </SidebarInset>
                        </SidebarProvider>
                    </ThemeProvider>
                </NeonAuthUIProvider>
            </body>
        </html >
    );
}
