import type { Metadata } from "next";
import { AppSidebar } from "@/components/navigation/sidebar";
import Header from "@/components/navigation/header";
import { SidebarInset, SidebarProvider } from "@/components/shadcn/sidebar";

import { Separator } from "@/components/shadcn/separator";


export const metadata: Metadata = {
    title: "Nifty Assignments",
    description: "Generated by create next app",
};

export default function ProtectedLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
                <Header />
                <Separator />
                <section className="flex flex-1 max-w-screen flex-col gap-4 p-0 pt-0 overflow-hidden">
                    {children}
                </section>
            </SidebarInset>
        </SidebarProvider>
    );
}
